apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-lobby
  labels:
    app: postgresdb-lobby
data:
  POSTGRES_DB: postgresdb-lobby
  POSTGRES_USER: lobby-user
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-lobby
  labels:
    app: postgresdb-lobby
data:
  POSTGRES_PASSWORD: bG9iYnlEQgo= #lobbyDB
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-lobby
  labels:
    type: local
    app: postgresdb-lobby
spec:
  storageClassName: standard
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/lobby-db-data/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim-lobby
  labels:
    app: postgresdb-lobby
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgresdb-lobby
  labels:
    app: postgresdb-lobby
spec:
  type: ClusterIP
  ports:
   - port: 5432
  selector:
   app: postgresdb-lobby
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb-lobby
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb-lobby
  template:
    metadata:
      labels:
        app: postgresdb-lobby
    spec:
      containers:
        - name: postgresdb-lobby
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: postgres-config-lobby
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: postgres-config-lobby
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-secret-lobby
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/
              name: postgredb-lobby
      volumes:
        - name: postgredb-lobby
          persistentVolumeClaim:
            claimName: postgres-pv-claim-lobby
