apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-play
  labels:
    app: postgresdb-play
data:
  POSTGRES_DB: postgresdb-play
  POSTGRES_USER: play-user
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-play
  labels:
    app: postgresdb-play
data:
  POSTGRES_PASSWORD: cGxheURCCg== #playDB
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-play
  labels:
    type: local
    app: postgresdb-play
spec:
  storageClassName: standard
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/play-db-data/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim-play
  labels:
    app: postgresdb-play
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgresdb-play
  labels:
    app: postgresdb-play
spec:
  type: ClusterIP
  ports:
   - port: 5432
  selector:
   app: postgresdb-play
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb-play
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb-play
  template:
    metadata:
      labels:
        app: postgresdb-play
    spec:
      containers:
        - name: postgresdb-play
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: postgres-config-play
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: postgres-config-play
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-secret-play
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb-play
      volumes:
        - name: postgredb-play
          persistentVolumeClaim:
            claimName: postgres-pv-claim-play
