# Static services 
kind: Service
apiVersion: v1
metadata:
  name: lobby-service
  labels:
    app: lobby
spec:
  selector:
    app: lobby
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: sample-service
  labels:
    app: sample
spec:
  selector:
    app: sample
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
kind: Service
apiVersion: v1
metadata:
  name: chat-service
  labels:
    app: chat
spec:
  selector:
    app: chat
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---
kind: Service
apiVersion: v1
metadata:
  name: webui-service
  labels:
    app: webui
spec:
  selector:
    app: webui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: play-service
  labels:
    app: play
spec:
  selector:
    app: play
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
--- # For testing the auth system in backend see issue 49
kind: Service
apiVersion: v1
metadata:
  name: test-service
  labels:
    app: test
spec:
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: oauth2-proxy
